# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginsys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='products.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('content', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='loginsys.UserProfile')),
            ],
            options={
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Manufacturer',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('creation_year', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('has_bluetooth', models.BooleanField(default=False)),
                ('has_wifi', models.BooleanField(default=False)),
                ('os_type', models.CharField(choices=[('win', 'Windows'), ('lin', 'Linux'), ('mac', 'MacOS'), ('ios', 'iOS'), ('and', 'Android'), ('win_p', 'Windows phone'), ('blb', 'BlackberryOS')], max_length=50)),
                ('categories', models.ManyToManyField(related_name='products', to='products.Category')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.Manufacturer')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('bc', 'black'), ('bn', 'brown'), ('be', 'blue'), ('yw', 'yellow'), ('rd', 'red'), ('pk', 'pink'), ('gn', 'green'), ('we', 'white'), ('gy', 'gray'), ('oe', 'orange')], max_length=50)),
                ('diagonal', models.FloatField()),
                ('material', models.CharField(choices=[('pc', 'polycarbonate'), ('al', 'aluminum'), ('st', 'steel'), ('gl', 'glass')], max_length=50)),
                ('image', models.ImageField(upload_to=products.models.get_upload_path)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SKUs', to='products.Product')),
            ],
            options={
                'verbose_name_plural': 'SKUs',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='products.Product'),
        ),
    ]
