# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_sku_stock_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sku',
            old_name='diagonal',
            new_name='screen_diagonal',
        ),
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='sku',
            name='material',
        ),
        migrations.AddField(
            model_name='product',
            name='battery_type',
            field=models.CharField(blank=True, choices=[('lipol', 'Li-Pol'), ('liion', 'Li-Ion'), ('nicd', 'Ni-Cd'), ('nimh', 'Ni-MH')], default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='builtin_memory',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='camera',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='connectors',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cores_count',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='processor',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ram',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='battery_capacity',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='sku',
            name='body_material',
            field=models.CharField(choices=[('pc', 'Polycarbonate'), ('al', 'Aluminum'), ('st', 'Steel'), ('gl', 'Glass')], default='pc', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sku',
            name='screen_resolution',
            field=models.CharField(default='0', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sku',
            name='weight',
            field=models.IntegerField(default=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='creation_year',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='os_type',
            field=models.CharField(blank=True, choices=[('win7', 'Windows 7'), ('win8', 'Windows 8'), ('win10', 'Windows 10'), ('lin', 'Linux'), ('mcos', 'Mac OS X'), ('ios', 'iOS'), ('and', 'Android'), ('winp', 'Windows phone'), ('blckb', 'Blackberry OS'), ('wtch', 'Watch OS')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sku',
            name='color',
            field=models.CharField(choices=[('bk', 'Black'), ('bn', 'Brown'), ('be', 'Blue'), ('yw', 'Yellow'), ('rd', 'Red'), ('pk', 'Pink'), ('pe', 'Purple'), ('gn', 'Green'), ('we', 'White'), ('gy', 'Gray'), ('oe', 'Orange')], max_length=50),
        ),
    ]
