# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20170615_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='builtin_memory',
            field=models.IntegerField(blank=True, default=None, help_text='In gigabytes', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='camera',
            field=models.IntegerField(blank=True, default=None, help_text='In mega pixels', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ram',
            field=models.IntegerField(blank=True, default=None, help_text='In gigabytes', null=True),
        ),
        migrations.AlterField(
            model_name='sku',
            name='battery_capacity',
            field=models.IntegerField(blank=True, default=None, help_text='In Milliamp * hour', null=True),
        ),
        migrations.AlterField(
            model_name='sku',
            name='screen_resolution',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sku',
            name='weight',
            field=models.IntegerField(help_text='In grams'),
        ),
    ]
