# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20170622_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sku',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='sku',
            name='screen_resolution',
            field=models.CharField(blank=True, help_text='Format: 640x480', max_length=50, null=True),
        ),
    ]
