# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20170626_1216'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('count', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='products.SKU')),
            ],
            options={
                'verbose_name_plural': 'Batches',
            },
        ),
    ]
