# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 09:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20170628_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='time',
        ),
        migrations.AddField(
            model_name='sku',
            name='batch',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sku', to='products.Batch'),
        ),
    ]
