# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20170629_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='cost',
            field=models.IntegerField(),
        ),
    ]
